[server]
# Dòng này cho phép Streamlit phục vụ tất cả các file từ thư mục gốc
# bao gồm cả thư mục 'songs'. Bạn có thể truy cập chúng qua URL: /app/songs/background1.mp3
# Tuy nhiên, cách an toàn hơn là sử dụng 'folder' bên dưới
# enableCORS = true 

# Cấu hình cụ thể để phục vụ một thư mục bất kỳ dưới một URL cơ sở.
# Chúng ta sẽ phục vụ thư mục "songs" dưới URL "/songs"
static_folder = "songs"
